# Generated by Django 4.0.5 on 2022-07-09 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('Owner', 'Owner'), ('District Manager', 'District_Manager'), ('Manager', 'Manager'), ('Assistant_Manager', 'Assistant_Manager'), ('Employee', 'Employee')], default='Employee', max_length=255)),
                ('user_address', models.CharField(max_length=255)),
                ('user_city', models.CharField(max_length=255)),
                ('user_state', models.CharField(max_length=255)),
                ('user_zip_code', models.CharField(max_length=255)),
                ('user_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user_emial', models.CharField(blank=True, max_length=255, null=True)),
                ('foreign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sick_time_max', models.DecimalField(decimal_places=2, default=48, max_digits=5)),
                ('sick_time_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sick_time_current', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sick_time_accural_rate', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('hire_date', models.DateField()),
                ('is_terminated', models.BooleanField(default=False)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Extension',
                'verbose_name_plural': 'User Extensions',
            },
        ),
    ]
