# Generated by Django 4.0.5 on 2022-07-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise_entity',
            name='employees',
            field=models.ManyToManyField(blank=True, to='users.userextension'),
        ),
        migrations.AddField(
            model_name='franchise_entity',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.franchise'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
